### PR TITLE
fix: onBlur event is getting fired for readOnly form elements.

### PR DESCRIPTION
**Pull request by tumms2021389**

### CODE REVIEW

**Comment by JEAxero** [comment]
@tumms2021389 @vrseraphin  What are the plans for fixing this in SDK-A and SDK-WC while it's top of mind?

**Review by JEAxero — APPROVED** [review]
Ran tests. Looks good to me.

**Review by JEAxero — APPROVED** [review]
Ran tests. Looks good to me.

**Comment by tumms2021389** [comment]
> @tumms2021389 @vrseraphin What are the plans for fixing this in SDK-A and SDK-WC while it's top of mind?

I will try to create a story to check this issue in other SDK's as well.

**Comment by JEAxero** [comment]
> > @tumms2021389 @vrseraphin What are the plans for fixing this in SDK-A and SDK-WC while it's top of mind?
> 
> I will try to create a story to check this issue in other SDK's as well.

Thanks!

**Pull request merged**
