### PR TITLE
E2E automation test for portal & embedded

### PR DESCRIPTION
**Pull request by vishalshrm539**
E2E automation test for portal & embedded

### CODE REVIEW

**Comment by JEAxero** [comment]
I'll test this soon to make sure the changes for tests don't affect the runtime of my normal use. One question when I took a quick look at the code: I see that we're getting testId passed in as a prop to many of the presentation components and there's no default value. Do you think it matters if the testId is undefined or would be it better to have a default value for the testId in the prop destructuring?

**Comment by vishalshrm539** [comment]
> I'll test this soon to make sure the changes for tests don't affect the runtime of my normal use. One question when I took a quick look at the code: I see that we're getting testId passed in as a prop to many of the presentation components and there's no default value. Do you think it matters if the testId is undefined or would be it better to have a default value for the testId in the prop destructuring?

I don't think we need to have a default value as such since that doesn’t add anything to selecting a particular element, but can see if we need that. If we don’t find a test-id for a field at the time of testing then out test will stuck and will eventually fail after timeout.

**Review by JEAxero — CHANGES_REQUESTED** [review]
We should add a section to the README (probably just before the "Some setup and troubleshooting tips" section) that explains how to run the tests and a brief description of what the tests do.

**Review by JEAxero — APPROVED** [review]
Ok to merge. However, we should get an updated kit with the updated MediaCo app (with the test IDs) out soon.

**Comment by vishalshrm539** [comment]
> Ok to merge. However, we should get an updated kit with the updated MediaCo app (with the test IDs) out soon.

Yes, I'll add testIDs on master.

**Pull request merged**
