### PR TITLE
Coming soon message in README

### PR DESCRIPTION
**Pull request by JEAxero**

### CODE REVIEW

**Review by niallriddell — CHANGES_REQUESTED** [review]
Can we add a link to https://docs.pega.com/bundle/constellation-sdk/page/constellation-sdks/sdks/react-sdk-updates.html for further informaiton please.

**Comment by JEAxero** [comment]
> Can we add a link to https://docs.pega.com/bundle/constellation-sdk/page/constellation-sdks/sdks/react-sdk-updates.html for further informaiton please.

See latest commit that addressing this suggestion.

**Review by niallriddell — APPROVED** [review]
Looks great.

**Review by syedi2 — COMMENTED** [review]
It will be good to add the release names as a bullet list first, at line 20 here. You can then continue the paragraphs from line 21 as it is, or add each release's description after each bullet.

**Pull request merged**
