### PR TITLE
Proposed change to EmbeddedData test

### PR DESCRIPTION
**Pull request by JEAxero**

### CODE REVIEW

**Review by 4manasa — APPROVED** [review]
Ran the tests in my local and All the testcases passed

**Review by vishalshrm539 — COMMENTED** [review]
I think, we should change input => td in lines 282 to 285 as well.

**Comment by JEAxero** [comment]
> I think, we should change input => td in lines 282 to 285 as well.

Thanks for noticing that. I'll make that change and run the tests and push an updated commit if that works.

**Comment by JEAxero** [comment]
> > I think, we should change input => td in lines 282 to 285 as well.
> 
> Thanks for noticing that. I'll make that change and run the tests and push an updated commit if that works.

Just pushed those changes (after successfully testing locally). Please re-review and, if approved, I'll merge. Thanks!

**Review by vishalshrm539 — APPROVED** [review]

**Pull request merged**
