### PR TITLE
DetailsThreeColumn template support added

### PR DESCRIPTION
**Pull request by tumms2021389**
Screenshot 2022-11-02 at 12 10 30 AM

### CODE REVIEW

**Comment by JEAxero** [comment]
For next time, we're trying to use 3 letter abbrevs in branch names: mod/bug then spr/tor then ID.

**Comment by JEAxero** [comment]
@tumms2021389 How do I test this and will we be adding automation tests for this component in the near future?

**Comment by tumms2021389** [comment]
> @tumms2021389 How do I test this and will we be adding automation tests for this component in the near future?

**Comment by tumms2021389** [comment]
Yes @JEAxero , we will be adding automation test cases for all View templates in the future. For now, you can test this by opening DigV2 app in lab0641 --> View Templates case type then you can see all Details Column templates which include Three column detail template

**Review by JEAxero — APPROVED** [review]
Tested on 0641. Looks good to me.

**Pull request merged**
