### PR TITLE
Fixed ToDo issues

### PR DESCRIPTION
**Pull request by vishalshrm539**
* Fixed the issue when we remove and add back ToDo widget from Home landing page.
* For more details, pls refer US-507637.

### CODE REVIEW

**Comment by vishalshrm539** [comment]
I'll be making fixes for this issue in other SDKs as well.

**Review by JEAxero — APPROVED** [review]
Couldn't get DigV2 EmbeddedData test to work but that doesn't seem to be related to this change. So, for me, it's ok to merge this and investigate the EmbeddedData test failure separately

**Comment by vishalshrm539** [comment]
> Couldn't get DigV2 EmbeddedData test to work but that doesn't seem to be related to this change. So, for me, it's ok to merge this and investigate the EmbeddedData test failure separately

I did run the tests and they were successful. Did you use lab0641 to run the tests?

**Comment by JEAxero** [comment]
> > Couldn't get DigV2 EmbeddedData test to work but that doesn't seem to be related to this change. So, for me, it's ok to merge this and investigate the EmbeddedData test failure separately
> 
> I did run the tests and they were successful. Did you use lab0641 to run the tests?

Yes, I ran them against 0641 and, for me, the EmbeddedData test failed. Once I pull the latest changes (including these) again, I'll try again.

**Pull request merged**
