### PR TITLE
Issues in data reference or read only tables fixed

### PR DESCRIPTION
**Pull request by 4manasa**

### CODE REVIEW

**Comment by JEAxero** [comment]
See the failed check for some lint problems that need to be addressed. Also, will this fix need to also be ported to the react-sdk-components repo?

**Review by JEAxero — CHANGES_REQUESTED** [review]
See the failed check for some lint problems that need to be addressed.

Also, will this fix need to also be ported to the react-sdk-components repo?

**Comment by JEAxero** [comment]
> See the failed check for some lint problems that need to be addressed.
> 
> Also, will this fix need to also be ported to the react-sdk-components repo?

After the 2nd commit to fix the lint errors, the Github action (and confirmed on my local system when I pulled this branch) is still failing. As noted in the lint failure message: you can't put const/let/var declarations inside in the switch statement's "case" block.

**Comment by 4manasa** [comment]
> > See the failed check for some lint problems that need to be addressed.
> > Also, will this fix need to also be ported to the react-sdk-components repo?
> 
> After the 2nd commit to fix the lint errors, the Github action (and confirmed on my local system when I pulled this branch) is still failing. As noted in the lint failure message: you can't put const/let/var declarations inside in the switch statement's "case" block.

Fixed the lint errors and added the fix in react-sdk-components repo as well.

**Review by JEAxero — APPROVED** [review]
Reviewed. Tested. Looks good.

**Pull request merged**
