### PR TITLE
Added playwright tests for data reference views

### PR DESCRIPTION
**Pull request by vishalshrm539**
* Added playwright tests for data reference views.
* Refer US-488539 for more details.

### CODE REVIEW

**Comment by vishalshrm539** [comment]
Please use lab0641 server with user.digv2/pega credentials to exercise these tests.

**Review by JEAxero — CHANGES_REQUESTED** [review]
Tests that are implemented pass when I run against the Labs machine. However, since there are some DataReference features that don't have tests yet (due to not being in the test app yet or not yet implemented), I was thinking that we may want to include some TODO comments or similar in the test file to remind us of what features are **not** covered by these newly added tests. If there's a better reminder system, that's ok. I just want a way for us to remember that more tests will need to be added here.

**Comment by vishalshrm539** [comment]
I've mentioned the tests that are missing in the US-488539 already. Not sure if that is good enough?

**Comment by vishalshrm539** [comment]
> Tests that are implemented pass when I run against the Labs machine. However, since there are some DataReference features that don't have tests yet (due to not being in the test app yet or not yet implemented), I was thinking that we may want to include some TODO comments or similar in the test file to remind us of what features are **not** covered by these newly added tests. If there's a better reminder system, that's ok. I just want a way for us to remember that more tests will need to be added here.

Yes, there is an issue with the RAP. I checked it by importing on another server and the problem is records of various data objects are missing that's why we're not seeing any option in the dropdown.

**Comment by JEAxero** [comment]
> I've mentioned the tests that are missing in the US-488539 already. Not sure if that is good enough?

Ok. Let's just make the effort to track the tests that remain to be done in our backlog. Maybe create a new story in the backlog as a reminder for us.

**Review by JEAxero — APPROVED** [review]

**Comment by vishalshrm539** [comment]
> > I've mentioned the tests that are missing in the US-488539 already. Not sure if that is good enough?
> 
> Ok. Let's just make the effort to track the tests that remain to be done in our backlog. Maybe create a new story in the backlog as a reminder for us.

Sure, will do that.

**Pull request merged**
