### PR TITLE
8.7 auth upgrades

### PR DESCRIPTION
**Pull request by vrseraphin**
Improved authentication using authorization code with PKCE
Simplification of sdk-config.json file
Revoke tokens on logout
Browser reload without reauthentication

### CODE REVIEW

**Comment by JEAxero** [comment]
It looks like something isn't quite right when I reload /embedded after completing a run through an /embedded use. Perhaps one of the bShowPega, bShowTriplePlayOptions settings isn't getting set back correctly. As shown in the attached screenshot, I can get it in the state when - after reload - clicking a Shop Now button shows the buttons *and* the page where the Pega flow should be. At point, I have to click the Shop Now button again.
Screen Shot 2022-01-28 at 8 21 29 AM

**Comment by vrseraphin** [comment]
A .har file is useful if you encounter such issues.  Until re-authentication is supported, you limited to the length of time specified by the access token within the OAuth 2.0 client registration record.  Curious whether the 15 minutes had expired since you did the initial authorization?
After which reloading the screen should be fine, more work will happen in future around handling the token expirations and refreshes.

**Comment by JEAxero** [comment]
The 15 minutes hadn't expired. I went through the flow to the end and then refreshed the page (my normal use). I'll grab a .har file but will approve the PR for now since it seems like an edge case. Thanks!

**Review by JEAxero — APPROVED** [review]
I'll send along a .har file but approving since this seems to be an edge case.

**Pull request merged**
