### PR TITLE
Mashm/attachment

### PR DESCRIPTION
**Pull request by 4manasa**
added a control to upload attachments in react SDK
Add link functionality and css changes need to be done

### CODE REVIEW

**Review by JEAxero — APPROVED** [review]

**Review by tumms2021389 — APPROVED** [review]

**Comment by JEAxero** [comment]
@tumms2021389 @4manasa Why did the changes get pushed again? I'm assuming nothing new is in the files that were jsut pushed.

**Comment by tumms2021389** [comment]
> @tumms2021389 @4manasa Why did the changes get pushed again? I'm assuming nothing new is in the files that were just pushed.

There are no changes in the latest commits, I have done rebase the current branch with the main branch as there were some conflicts with the main branch. Now the commits look more clear and there won't be any duplicate commits in the logs.

Attached is the screenshot of previous commits history before rebase for comparing
[
Screenshot 2022-04-08 at 12 15 00 AM
](url)

**Comment by tumms2021389** [comment]
It is always good practice to do rebasing the feature branch with the base branch whenever you see merge conflicts in the git instead of doing a merge commit. It actually avoids unnecessary merge commits to the log history and makes commit logs cleaner.

**Comment by JEAxero** [comment]
Ok. I didn't realize that rebase would look like all of the earlier commits got repeated. Earlier there were no indications of a merge conflict but, if there were, we obviously had to fix them. And we typically due "squash and merge" to make it easier to see what happened overall. So, that should also help the commit/PR be easier to understand. Thanks for the explanation.

**Comment by 4manasa** [comment]
not fully complete will address CSS and links functionality in next PR

**Pull request merged**
